### ISSUE TITLE
Stray "foo"

### ISSUE THREAD

**Issue by lapo-luchini** [Luzilla/dnsbl_exporter#107]
I get this in `/metrics/`:

```
# HELP luzilla_rbls_listed The number of listings in RBLs (this is bad)
# TYPE luzilla_rbls_listed gauge
luzilla_rbls_listed{rbl="foo"} 1
# HELP luzilla_rbls_used The number of RBLs to check IPs against (configured via rbls.ini)
# TYPE luzilla_rbls_used gauge
luzilla_rbls_used 86
```

I know no Go, but I guess [this might the problem](https://github.com/Luzilla/dnsbl_exporter/blob/c0b2b3bd069c7519f2f6bdfb3971734df34c95e6/collector/collector.go#L123).

PS: nice exporter, will be useful to me, thanks!

**Comment by till** [comment]
@lapo-luchini Thanks for reporting. And glad that you like it. I'll take a look tomorrow. :)

**Comment by till** [comment]
Sorry, got a bit derailed with the C-thing. Looking at this soon.

**Comment by till** [comment]
@lapo-luchini I made a PR, the `foo` is gone, it will now show this (I just forgot to add this):

```
# HELP luzilla_rbls_listed The number of listings in RBLs (this is bad)
# TYPE luzilla_rbls_listed gauge
luzilla_rbls_listed{rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_listed{rbl="zen.spamhaus.org"} 0
```

As an aggregate how many listing each has, and to keep track of it over time.

**Comment by till** [comment]
This is released in: https://github.com/Luzilla/dnsbl_exporter/releases/tag/v0.6.0-alpha1
