### ISSUE TITLE
Crash after running a few days

### ISSUE THREAD

**Issue by lapo-luchini** [Luzilla/dnsbl_exporter#108]
```
ERRO[357497]
ERRO[358096]
ERRO[358096]
ERRO[358096]
ERRO[358098]
ERRO[358696]
ERRO[359597]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46f1d3]

goroutine 213683 [running]:
github.com/Luzilla/dnsbl_exporter/collector.(*Rbl).lookup(0xc0002c0030, {0xc000230420, 0xc}, {0xc000230550, 0xc})
        /home/lapo/dnsbl_exporter/collector/rbl.go:163 +0x4b9
github.com/Luzilla/dnsbl_exporter/collector.(*Rbl).Update.func1(0xc0000b2000, 0xc0002c0030, {0xc000230420, 0xc}, {0xc000230550, 0xc})
        /home/lapo/dnsbl_exporter/collector/rbl.go:181 +0x16d
created by github.com/Luzilla/dnsbl_exporter/collector.(*Rbl).Update
        /home/lapo/dnsbl_exporter/collector/rbl.go:176 +0x105
```

**Comment by till** [comment]
Can you share your config?

**Comment by lapo-luchini** [comment]
I used [the full file from matteocorti](https://github.com/matteocorti/check_rbl/blob/master/check_rbl.ini) as `rbls.ini` and I have two servers in my `targets.ini`.

**Comment by till** [comment]
@lapo-luchini looking at this again too. I am assuming the crash still happens. I'll see if I can re-do the code and make it more easier to handle _failures_.

**Comment by till** [comment]
@lapo-luchini again, sorry for the delay. I made a branch and hopefully included a fix, not sure if you want/can test: #119 

I will merge it later and release a new version. If you happen to run into other issues, please run the process with `--log.debug`. It should help me catch what the problem is. My guess here is that some kind of (temporary?) failure in DNS resolution or record lookup made it crash.

**Comment by till** [comment]
https://github.com/Luzilla/dnsbl_exporter/releases/tag/v0.6.0-alpha1

**Comment by lapo-luchini** [comment]
I'm testing 9088e8b3a7e4a24056cb9d8e81fa8803f1086a44, thanks!

Will report if I find bugs (or it crashes again).

**Comment by lapo-luchini** [comment]
Happened again (after quite a few straight days of running):

```
ERRO[430346]
ERRO[431246]
ERRO[431846]
ERRO[432147]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x465473]

goroutine 257028 [running]:
github.com/Luzilla/dnsbl_exporter/collector.(*Rbl).lookup(0xc0001f76e0, {0xc00002a5d0, 0x12}, {0xc0000293d0, 0xc})
        /home/andxor/dnsbl_exporter/collector/rbl.go:163 +0x36f
github.com/Luzilla/dnsbl_exporter/collector.(*Rbl).Update.func1({0xc00002a5d0, 0x12}, {0xc0000293d0, 0xc})
        /home/andxor/dnsbl_exporter/collector/rbl.go:181 +0x12f
created by github.com/Luzilla/dnsbl_exporter/collector.(*Rbl).Update
        /home/andxor/dnsbl_exporter/collector/rbl.go:176 +0x18a
% git describe
0.5.0-53-g9088e8b
```

**Comment by lapo-luchini** [comment]
Whops, sorry, you said to try the branch and I was trying head… switching now to this:

```
% git checkout origin/fix-nil-pointer
% git describe
v0.6.0-alpha3
```

**Comment by till** [comment]
@lapo-luchini Appreciate the persistence! 💪

**Comment by till** [comment]
@lapo-luchini Hope no news is good news? 😅

**Comment by lapo-luchini** [comment]
Yeah sorry, it seems it never happened again.

**Comment by till** [comment]
> Yeah sorry, it seems it never happened again.

Thank you!
