### ISSUE TITLE
Support multi-target exporter pattern

### ISSUE THREAD

**Issue by DrMurx** [Luzilla/dnsbl_exporter#127]
Feature proposal: 

Support the [multi-target exporter pattern](https://prometheus.io/docs/guides/multi-target-exporter/) so that the targets can be defined (or discovered) in the Prometheus config instead of `target.ini`.

**Comment by till** [comment]
@DrMurx Sounds good, do you want to help?

**Comment by till** [comment]
@DrMurx If you wanna have a look, I created a PR. It was easier than expected.

**Comment by DrMurx** [comment]
@till Didn't test in real conditions, but the code LGTM :-)
