### ISSUE TITLE
Add an ability to use the certain black list to query only domain names

### ISSUE THREAD

**Issue by zentavr** [Luzilla/dnsbl_exporter#167]
There are a certain black list which contain **only** the domains, but not IPs. I.E.: `dbl.spamhaus.org`. From [DBL FAQ](https://www.spamhaus.org/faq/section/Spamhaus%20DBL) they mention:
- The Spamhaus DBL is a list of domain names with poor reputations. It is published in a domain DNSBL format. These domain reputations are calculated from many factors, and maintained in a database which in turn feeds the DBL zone itself.
- It **ONLY** lists domains. No IP addresses are listed by the DBL.
- The DBL is a domain-only blocklist and does not include or support IP addresses. 
- An IP query against the DBL always returns a positive (listed) return code

It would be great to have a separate list file which would be used only for these kind of checks

**Comment by till** [comment]
Hadn't heard of this. Will read up on this later.
