### ISSUE TITLE
segfaults caused by not checking return values of err

### ISSUE THREAD

**Issue by maznu** [Luzilla/dnsbl_exporter#17]
Thanks for `dnsbl_exporter`, it's fantastic and looks to be just the tool I'm looking for.

I've encountered the potential for it to segfault, though:

```
time="2019-12-15T23:06:46Z" level=info msg="We had an ip XXX.XXX.XXX.XXX"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x836a8b]
goroutine 33 [running]:
github.com/luzilla/dnsbl_exporter/collector.(*Rbl).getARecords(0xc00006fe90, 0xc000092210, 0x23, 0x2, 0x2, 0xc000092210, 0x23, 0xc000090a00)
#011/Users/till/Documents/workspaces/luzilla/dnsbl_exporter/collector/rbl.go:65 +0x8b
github.com/luzilla/dnsbl_exporter/collector.(*Rbl).query(0xc00006fe90, 0xc000090a00, 0xc, 0xc000026a80, 0x16, 0xc0001f7ea8)
#011/Users/till/Documents/workspaces/luzilla/dnsbl_exporter/collector/rbl.go:104 +0x1f9
github.com/luzilla/dnsbl_exporter/collector.(*Rbl).lookup(0xc00006fe90, 0xc000026a80, 0x16, 0xc000022450, 0xc, 0x1, 0x1, 0x0)
#011/Users/till/Documents/workspaces/luzilla/dnsbl_exporter/collector/rbl.go:145 +0x2ca
github.com/luzilla/dnsbl_exporter/collector.(*Rbl).Update.func1(0xc0000909a0, 0xc00006fe90, 0xc000026a80, 0x16, 0xc000022450, 0xc)
#011/Users/till/Documents/workspaces/luzilla/dnsbl_exporter/collector/rbl.go:166 +0x133
created by github.com/luzilla/dnsbl_exporter/collector.(*Rbl).Update
#011/Users/till/Documents/workspaces/luzilla/dnsbl_exporter/collector/rbl.go:161 +0xf0
```

I'm guessing that this is because `getARecords` does not check the value of `err` on line 61, before it goes and tries to iterate through the response.

Would you like me to submit a PR to handle some of the missing checks?

**Comment by till** [comment]
@maznu terribly sorry that I missed this. Yes, of course you can submit a PR! :)

**Comment by till** [comment]
Seems like it's as easy to reproduce as to add something in `targets.ini` that doesn't exist:

```
server=does.not.exist.fqdn
```

Fixing now. :)

**Comment by till** [comment]
Now, the question is if we want to elevate these errors to `/metrics`? I'll leave this ticket open for a while in case you want to discuss.

**Comment by till** [comment]
@maznu fixed in master, I'll do a release after I refactored some error handling.

**Comment by till** [comment]
0.4.1 is released

**Comment by maznu** [comment]
Sorry for the delay getting back to you — have been away working. I'm conflicted — hugely grateful that you fixed this, but I guess I'll have to find some other low-hanging-fruit to be my first reason to learn some Go ;)

Thank you again, shall test and let you know how we get on!

**Comment by till** [comment]
@maznu 😆 — let me know how it works. Other contributions certainly welcome. Let me know.
